# Generated by Django 4.1.7 on 2023-03-30 03:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mobile',
            field=models.CharField(blank=True, default='', help_text='<small class="text-muted">CharField [0, 12]</small><hr><br>', max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(12)], verbose_name='Мобильный'),
        ),
    ]
